export const ContactActionTypes = {
  FEEDBACK_REQUEST: "FEEDBACK_REQUEST",
  CREATE_FEEDBACK_SUCCESS: "CREATE_FEEDBACK_SUCCESS",
  CREATE_FEEDBACK_FAILURE: "CREATE_FEEDBACK_FAILURE",
  GET_FEEDBACK_REQUEST: "GET_FEEDBACK_REQUEST",
  GET_FEEDBACK_SUCCESS: "GET_FEEDBACK_SUCCESS",
  GET_FEEDBACK_FAILURE: "GET_FEEDBACK_FAILURE",
};
