export const WishListActionTypes = {
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  CLEAR_ITEM_FROM_WISHLIST: "CLEAR_ITEM_FROM_WISHLIST",
  CLEAR_ALL_ITEMS_FROM_WISHLIST: "CLEAR_ALL_ITEMS_FROM_WISHLIST",
};
